# Generated by Django 2.0.5 on 2018-08-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobosevents', '0011_userevent_confirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevent',
            old_name='bike_year',
            new_name='age_on_event_day',
        ),
        migrations.RenameField(
            model_name='userevent',
            old_name='placard',
            new_name='rider_number',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='bike_model',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userevent',
            name='start_time',
            field=models.TimeField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userspecialtest',
            name='total_time',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='specialtest',
            name='special_test_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='ama_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='omra_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
